format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[username]
show_always = true
format = "[$user]($style)@"
style_user = "bold green"
style_root = "bold red"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold cyan"
trim_at = "."

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold blue"
truncation_length = 4
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold purple"
symbol = " "

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold yellow"

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "
style = "bold yellow"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
